import AppBar from '../components/appbar';
import './global.css';

export const metadata = {
  title: 'Welcome to my-shop',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <AppBar />
        {children}
      </body>
    </html>
  );
}
